# Dependencies


# Permalinks
permalink:        pretty


# Setup
title:            Analysis of Global and Regional Remittance Flow
tagline:          ''
description:      'A 2022 Project for CYPLAN 255 at the University of California, Berkeley'
url:              "https://janeluke.github.io"
baseurl:          "/CP255_Project/"

theme: jekyll-theme-slate

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/janeluke/CP255_Project/

